# Generated by Django 2.2 on 2021-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
