# Generated by Django 2.2 on 2021-05-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_causegroup_groupinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causegroup',
            name='participants',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='accounts.CauseGroup'),
        ),
    ]
