# Generated by Django 2.2 on 2021-05-14 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210513_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='percentBPS',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
