# Generated by Django 3.1.7 on 2021-03-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210312_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eth_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
