# Generated by Django 3.1.7 on 2021-03-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210315_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eth_private_key',
            new_name='ethereum_private_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eth_public_key',
            new_name='ethereum_public_key',
        ),
    ]
